Farmback 12 add routes app name
WildCodeSchool/2103-lille-js-p3-farmconnect-backend pull request #17
Opened 2021-07-13 13:57 UTC by Erriep

2021-07-13 14:19 UTC, AntoineCAU approved these changes

2021-07-15 11:33 UTC, LoicBrassart requested changes
Remove a todo

2021-07-15 11:33 UTC, LoicBrassart commented on routes/appfav.js
> +    // TODO
Remove this comment: If it's something "to do", **do it** !

2021-07-15 11:58 UTC, LoicBrassart approved these changes
SnE

2021-07-15 12:45 UTC, merged