Farmback 04 init passport
WildCodeSchool/2103-lille-js-p3-farmconnect-backend pull request #5
Opened 2021-06-17 10:50 UTC by Erriep

2021-06-17 12:21 UTC, AntoineCAU approved these changes

2021-06-17 12:21 UTC, AntoineCAU commented
Nice job Pierre !

2021-06-17 14:55 UTC, LoicBrassart requested changes
Code to remove

2021-06-17 14:55 UTC, LoicBrassart commented on passport-strategies.js
> +        console.log(e);
No `console.log`, delete it

2021-06-17 14:55 UTC, LoicBrassart commented on routes/auth.js
> +
useless empty line

2021-06-17 14:55 UTC, LoicBrassart commented on routes/auth.js
> +    console.log(e);
no console.log

2021-06-17 14:55 UTC, LoicBrassart commented on routes/misc.js
> +
useless empty line

2021-06-17 14:55 UTC, LoicBrassart commented on routes/misc.js
> +});
Useless routes

2021-06-22 09:04 UTC, Erriep commented on routes/auth.js
> +
es-lint force this :(

2021-06-22 09:05 UTC, Erriep commented on routes/misc.js
> +
es-lint force this :(

2021-06-22 09:34 UTC, AntoineCAU approved these changes

2021-06-23 08:28 UTC, LoicBrassart requested changes
One route to delete

2021-06-23 08:28 UTC, LoicBrassart commented on routes/misc.js
> +});
Useless route on this project

2021-06-23 11:58 UTC, AntoineCAU approved these changes

2021-06-24 08:53 UTC, LoicBrassart approved these changes
Better!

2021-06-24 09:15 UTC, merged