Farmback 05 loginsecure
WildCodeSchool/2103-lille-js-p3-farmconnect-backend pull request #6
Opened 2021-06-24 09:09 UTC by Erriep

2021-06-24 09:23 UTC, AntoineCAU approved these changes

2021-06-25 13:56 UTC, LoicBrassart requested changes
Please re-read what you did

2021-06-25 13:56 UTC, LoicBrassart commented on routes/misc.js
> +});
Useless route

2021-06-30 09:35 UTC, LoicBrassart approved these changes
SnE!

2021-07-01 07:05 UTC, merged